services:
  nginx:
    # nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - php
    volumes:
      - ../src/:/var/www/html
      - ../front/output:/var/www/front/output
    networks:
      - default

  php:
    # php(laravel)
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ../src/:/var/www/html

  mariadb:
    # mariadb
    build:
      context: .
      dockerfile: ./mariadb/Dockerfile
    ports:
      - ${MARIADB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    networks:
      - default
    volumes:
      - db-store:/var/lib/mysql

  adminer:
    # adminer
    image: adminer:latest
    environment:    
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DESIGN: ng9    
    ports:
      - 8081:8080

networks:
  default:
    name: container_network

volumes:
  db-store: